apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service-chart.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "order-service-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "order-service-chart.name" . }}
