replicaCount: 2

.Release:
  Namespace:order-service
image:
  repository: vpn12345/order-service
  tag: 0.0.1
  pullPolicy: Always
imagePullSecrets:
  - name: doccred
service:
  type: NodePort
  port: 8081
serviceAccount:
  create: true
  name: ""
configMapName: order-config
secretName: order-db-secret
env:
  DB_USERNAME: orderuser
  DB_PASSWORD: orderpass

